/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface BlinkBlink {
      'interval': number;
    }
  }

  interface HTMLBlinkBlinkElement extends StencilComponents.BlinkBlink, HTMLStencilElement {}

  var HTMLBlinkBlinkElement: {
    prototype: HTMLBlinkBlinkElement;
    new (): HTMLBlinkBlinkElement;
  };
  interface HTMLElementTagNameMap {
    'blink-blink': HTMLBlinkBlinkElement;
  }
  interface ElementTagNameMap {
    'blink-blink': HTMLBlinkBlinkElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'blink-blink': JSXElements.BlinkBlinkAttributes;
    }
  }
  namespace JSXElements {
    export interface BlinkBlinkAttributes extends HTMLAttributes {
      'interval'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
