/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BlinkBlink {
    'interval': number;
  }
}

declare global {


  interface HTMLBlinkBlinkElement extends Components.BlinkBlink, HTMLStencilElement {}
  var HTMLBlinkBlinkElement: {
    prototype: HTMLBlinkBlinkElement;
    new (): HTMLBlinkBlinkElement;
  };
  interface HTMLElementTagNameMap {
    'blink-blink': HTMLBlinkBlinkElement;
  }
}

declare namespace LocalJSX {
  interface BlinkBlink {
    'interval'?: number;
  }

  interface IntrinsicElements {
    'blink-blink': BlinkBlink;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'blink-blink': LocalJSX.BlinkBlink & JSXBase.HTMLAttributes<HTMLBlinkBlinkElement>;
    }
  }
}


